(function () {
  'use strict';
  const $ = (s, el = document) => el.querySelector(s), $$ = (s, el = document) => [...el.querySelectorAll(s)];
  let report = null, toastTimer;
  const esc = s => String(s ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const empty = (title, body) => `<div class="empty-state"><div class="empty-icon">◇</div><strong>${esc(title)}</strong>${esc(body)}</div>`;
  const hostSelect = (items, value) => items.map(h => `<option value="${esc(h.address)}" ${h.address === value ? 'selected' : ''}>${esc(h.address)}</option>`).join('');
  function toast(message) { const el = $('#toast'); el.textContent = message; el.classList.add('show'); clearTimeout(toastTimer); toastTimer = setTimeout(() => el.classList.remove('show'), 2800); }
  function safeURL(text) { try { const u = new URL(text); return ['http:', 'https:'].includes(u.protocol) ? u.href : ''; } catch { return ''; } }
  function showTab(tab) {
    $$('.nav-item').forEach(b => b.classList.toggle('active', b.dataset.tab === tab));
    $$('.tab-content').forEach(el => { el.hidden = el.id !== `tab-${tab}`; });
  }
  function metrics() {
    const ports = report.hosts.flatMap(h => h.ports.map(p => ({ ...p, host: h.address, hostname: h.hostname })));
    const open = ports.filter(p => p.state === 'open');
    return { ports, open, services: [...new Set(open.map(p => p.service).filter(x => x && x !== 'unknown'))] };
  }
  function render() {
    const m = metrics(), { hosts, scan, findings, scripts, web } = report;
    $('#nav-hosts').textContent = hosts.length; $('#nav-ports').textContent = m.ports.length; $('#nav-findings').textContent = findings.length; $('#nav-scripts').textContent = scripts.length; $('#nav-web').textContent = web.length;
    $('#scan-name').textContent = report.filename; $('#scan-meta').textContent = `${report.format.toUpperCase()} output · ${scan.date ? esc(scan.date) : 'Scan date not found'} · Parsed locally`;
    $('#upload-panel').hidden = true; $('#report').hidden = false; $('#replace-button').hidden = false;
    renderOverview(m); renderHosts(); renderPorts(m); renderFindings(); renderScripts(); renderWeb(); renderNetwork(); renderRaw();
    showTab('overview');
  }
  function renderOverview(m) {
    const { hosts, scan, findings, scripts, web, unparsed } = report;
    const topServices = m.open.reduce((acc,p) => (acc[p.service] = (acc[p.service] || 0) + 1, acc), {});
    const serviceBars = Object.entries(topServices).sort((a,b) => b[1]-a[1]).slice(0,5);
    const hostRows = hosts.slice(0,5).map(h => `<div class="host-row"><div class="host-sigil">⌘</div><div class="host-main"><strong>${esc(h.address)}</strong><span>${esc(h.hostname || 'No hostname reported')} · ${h.ports.filter(p=>p.state==='open').length} open ports</span></div><span class="state-pill ${esc(h.state)}">${esc(h.state)}</span></div>`).join('');
    const findingRows = findings.slice(0,4).map(f => `<div class="host-row"><span class="severity-pill ${esc(f.severity)}">${esc(f.severity)}</span><div class="host-main"><strong>${esc(f.title)}</strong><span>${esc(f.host)}${f.port ? ` · port ${f.port}` : ''}</span></div><span class="kind-pill reported">REPORTED</span></div>`).join('');
    $('#tab-overview').innerHTML = `<div class="report-heading"><div><h2>Scan overview</h2><p>What this report explicitly tells us.</p></div><span class="parsed-chip"><i></i> SOURCE: ${report.format.toUpperCase()}</span></div>
      <div class="cards"><div class="metric-card"><div class="metric-label">HOSTS FOUND</div><div class="metric-value">${scan.hostCount}</div><div class="metric-foot">${scan.upCount} reported up</div></div><div class="metric-card"><div class="metric-label">OPEN PORTS</div><div class="metric-value metric-accent">${scan.openCount}</div><div class="metric-foot">Across ${scan.portCount} port records</div></div><div class="metric-card"><div class="metric-label">SERVICES IDENTIFIED</div><div class="metric-value">${m.services.length}</div><div class="metric-foot">Distinct open-port service names</div></div><div class="metric-card"><div class="metric-label">EXPLICIT FINDINGS</div><div class="metric-value" style="color:${findings.length?'var(--amber)':'var(--text)'}">${findings.length}</div><div class="metric-foot">${findings.length ? 'Named by scan script output' : 'No explicit vulnerability labels parsed'}</div></div></div>
      <div class="section-grid"><section class="panel"><div class="panel-head"><h3>Hosts at a glance</h3><small>${hosts.length} TOTAL</small></div><div class="panel-body">${hostRows || empty('No hosts parsed', 'Check the raw output for unrecognized host sections.')}</div></section><section class="panel"><div class="panel-head"><h3>Open services</h3><small>${m.open.length} OPEN PORTS</small></div><div class="panel-body">${serviceBars.length ? `<div class="mini-bars">${serviceBars.map(([name,n],i)=>`<div><div class="bar-label"><span>${esc(name)}</span><span>${n}</span></div><div class="bar-track"><div class="bar-fill ${i===1?'blue':i===2?'amber':''}" style="width:${Math.max(4,n/Math.max(1,m.open.length)*100)}%"></div></div></div>`).join('')}</div>` : empty('No open ports reported', 'Only explicitly reported open ports are counted.')}</div></section></div>
      <div class="section-grid"><section class="panel"><div class="panel-head"><h3>Explicit vulnerability findings</h3><small>${findings.length} REPORTED</small></div><div class="panel-body">${findingRows || empty('No explicit vulnerability findings', 'The scan output contains no script text clearly labeling a vulnerability. This does not prove the host is secure.')}</div></section><section class="panel"><div class="panel-head"><h3>Parsing notes</h3><small>${unparsed.length} UNCLASSIFIED LINES</small></div><div class="panel-body"><div class="note-box"><strong>Evidence-first reporting.</strong> A service banner or version string is displayed as reported metadata; it is not treated as proof of a vulnerability. Severity appears only when script output includes an explicit level. Review the raw output for ${unparsed.length} lines the parser did not classify.</div></div></section></div>`;
  }
  function renderHosts() {
    const body = report.hosts.map(h=>`<tr><td class="mono">${esc(h.address)}</td><td>${esc(h.hostname || '—')}</td><td><span class="state-pill ${esc(h.state)}">${esc(h.state)}</span></td><td>${h.ports.filter(p=>p.state==='open').length}</td><td>${h.ports.length}</td><td>${h.os.length ? esc(h.os.join('; ')) : 'Not identified'}</td></tr>`).join('');
    $('#tab-hosts').innerHTML = `<div class="report-heading"><div><h2>Discovered hosts</h2><p>Host identity and state as reported by Nmap.</p></div></div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Address</th><th>Hostname</th><th>State</th><th>Open ports</th><th>Port records</th><th>OS information</th></tr></thead><tbody>${body || `<tr><td colspan="6">${empty('No host records', 'No host sections were recognized in this input.')}</td></tr>`}</tbody></table></div></section>`;
  }
  function renderPorts(m) {
    $('#tab-ports').innerHTML = `<div class="report-heading"><div><h2>Ports & services</h2><p>Reported port state, service name, and version banner.</p></div></div><section class="panel"><div class="search-row"><input class="search-input" id="port-search" placeholder="⌕  Search port, host, service or version" /><select class="filter-select" id="port-state"><option value="">All states</option><option>open</option><option>closed</option><option>filtered</option></select><select class="filter-select" id="port-protocol"><option value="">All protocols</option><option>tcp</option><option>udp</option></select></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Port</th><th>Host</th><th>State</th><th>Service</th><th>Version / banner</th><th>Interpretation</th></tr></thead><tbody id="port-rows"></tbody></table></div></section>`;
    const draw = () => { const q = $('#port-search').value.toLowerCase(), st=$('#port-state').value, pr=$('#port-protocol').value; const rows=m.ports.filter(p=>`${p.port} ${p.host} ${p.hostname} ${p.service} ${p.version}`.toLowerCase().includes(q)&&(!st||p.state===st)&&(!pr||p.protocol===pr)); $('#port-rows').innerHTML=rows.map(p=>`<tr><td class="mono">${p.port}/${esc(p.protocol)}</td><td class="mono">${esc(p.host)}</td><td><span class="state-pill ${p.state==='open'?'up':'unknown'}">${esc(p.state)}</span></td><td>${esc(p.service)}</td><td>${esc(p.version||'—')}</td><td><span class="kind-pill associated">VERSION-ASSOCIATED</span></td></tr>`).join('')||`<tr><td colspan="6">${empty('No matching ports', 'Change or clear the search and filters.')}</td></tr>`; };
    ['port-search','port-state','port-protocol'].forEach(id=>$('#'+id).addEventListener('input',draw)); draw();
  }
  function renderFindings() {
    const rows=report.findings.map(f=>`<tr><td><span class="severity-pill ${esc(f.severity)}">${esc(f.severity)}</span></td><td><span class="kind-pill reported">EXPLICIT</span></td><td class="script-name">${esc(f.title)}</td><td class="mono">${esc(f.host)}${f.port?`:${f.port}`:''}</td><td class="script-output">${esc(f.description)}</td></tr>`).join('');
    const associated=report.hosts.flatMap(h=>h.ports.filter(p=>p.version).map(p=>({h,p}))).map(({h,p})=>`<tr><td><span class="severity-pill info">INFO</span></td><td><span class="kind-pill associated">VERSION-ASSOCIATED</span></td><td>${esc(p.service)} version reported</td><td class="mono">${esc(h.address)}:${p.port}</td><td>${esc(p.version)}<br><span style="color:var(--muted)">Version metadata alone does not confirm a vulnerability.</span></td></tr>`).join('');
    $('#tab-findings').innerHTML=`<div class="report-heading"><div><h2>Findings</h2><p>Explicit script claims separated from version metadata.</p></div></div><section class="panel"><div class="panel-head"><h3>Explicitly labeled by script output</h3><small>${report.findings.length} ITEMS</small></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Severity label</th><th>Evidence type</th><th>Script</th><th>Target</th><th>Reported detail</th></tr></thead><tbody>${rows||`<tr><td colspan="5">${empty('No explicit vulnerability labels', 'No VULNERABLE, CVE identifier, or explicit exploitability label was recognized in script results.')}</td></tr>`}</tbody></table></div></section><section class="panel" style="margin-top:13px"><div class="panel-head"><h3>Version-associated observations</h3><small>${report.hosts.flatMap(h=>h.ports).filter(p=>p.version).length} BANNERS</small></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Severity</th><th>Evidence type</th><th>Observation</th><th>Target</th><th>Reported version</th></tr></thead><tbody>${associated||`<tr><td colspan="5">${empty('No version banners reported', 'The scan did not include a service product or version banner.')}</td></tr>`}</tbody></table></div></section>`;
  }
  function renderScripts() {
    const rows=report.scripts.map(s=>`<tr><td class="script-name">${esc(s.name)}</td><td class="mono">${esc(s.host)}${s.port?`:${s.port}`:''}</td><td class="script-output">${esc(s.output||'(No output text)')}</td><td><span class="kind-pill reported">SCAN OUTPUT</span></td></tr>`).join('');
    $('#tab-scripts').innerHTML=`<div class="report-heading"><div><h2>NSE script results</h2><p>Script output captured by this scan.</p></div></div><section class="panel"><div class="search-row"><input class="search-input" id="script-search" placeholder="⌕  Search script names, hosts or output" /></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Script</th><th>Target</th><th>Output</th><th>Source</th></tr></thead><tbody id="script-rows"></tbody></table></div></section>`;
    const draw=()=>{const q=$('#script-search').value.toLowerCase();const filtered=report.scripts.filter(s=>`${s.name} ${s.host} ${s.output}`.toLowerCase().includes(q));$('#script-rows').innerHTML=filtered.map(s=>`<tr><td class="script-name">${esc(s.name)}</td><td class="mono">${esc(s.host)}${s.port?`:${s.port}`:''}</td><td class="script-output">${esc(s.output||'(No output text)')}</td><td><span class="kind-pill reported">SCAN OUTPUT</span></td></tr>`).join('')||`<tr><td colspan="4">${empty('No matching script output', 'Search another term or clear the filter.')}</td></tr>`;}; $('#script-search').addEventListener('input',draw);draw();
  }
  function renderWeb() {
    const rows=report.web.map(s=>{const urls=[...s.output.matchAll(/https?:\/\/[^\s),]+/ig)].map(m=>m[0]);const safe=urls.map(u=>safeURL(u)).filter(Boolean);return `<tr><td class="script-name">${esc(s.name)}</td><td class="mono">${esc(s.host)}${s.port?`:${s.port}`:''}</td><td class="script-output">${esc(s.output||'(No output text)')}${safe.length?'<br>'+safe.map(u=>`<a class="web-link" href="${esc(u)}" target="_blank" rel="noopener noreferrer">${esc(u)}</a>`).join('<br>'):''}</td><td><span class="kind-pill reported">SCAN OUTPUT</span></td></tr>`}).join('');
    $('#tab-web').innerHTML=`<div class="report-heading"><div><h2>Web findings</h2><p>HTTP, TLS and URL related script output identified in this report.</p></div></div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Script</th><th>Target</th><th>Reported web detail</th><th>Evidence</th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('No web script results recognized', 'The scan output contains no HTTP or TLS script result detected by this parser.')}</td></tr>`}</tbody></table></div></section>`;
  }
  function renderNetwork() {
    const items=report.hosts.flatMap(h=>[...h.os.map(value=>({host:h.address,label:'OS identification',value})),...h.network.map(x=>({host:h.address,label:x.label,value:x.value}))]);
    const rows=items.map(x=>`<tr><td class="mono">${esc(x.host)}</td><td>${esc(x.label)}</td><td>${esc(x.value)}</td><td><span class="kind-pill reported">SCAN OUTPUT</span></td></tr>`).join('');
    $('#tab-network').innerHTML=`<div class="report-heading"><div><h2>OS & network</h2><p>Fingerprint, address, and route details explicitly present in the report.</p></div></div><section class="panel"><div class="table-wrap"><table class="data-table"><thead><tr><th>Host</th><th>Detail</th><th>Reported value</th><th>Evidence</th></tr></thead><tbody>${rows||`<tr><td colspan="4">${empty('No OS or network details parsed', 'OS detection and network metadata were not present in a recognized form.')}</td></tr>`}</tbody></table></div></section>`;
  }
  function renderRaw() { $('#tab-raw').innerHTML=`<div class="report-heading"><div><h2>Raw output</h2><p>Original input preserved as received.</p></div><button class="button button-outline" id="copy-raw">Copy raw text</button></div><section class="panel"><pre class="raw-output">${esc(report.raw)}</pre></section><section class="panel" style="margin-top:13px"><div class="panel-head"><h3>Unclassified non-empty lines</h3><small>${report.unparsed.length} LINES</small></div><div class="raw-output">${report.unparsed.length?esc(report.unparsed.join('\n')): 'Every non-empty line matched a recognized report pattern.'}</div></section>`; $('#copy-raw').addEventListener('click',async()=>{try{await navigator.clipboard.writeText(report.raw);toast('Raw output copied to clipboard.')}catch{toast('Clipboard access is unavailable in this browser.')}}); }
  async function loadFile(file) {
    if (!file) return; if (file.size > 20*1024*1024) { toast('That file is over the 20 MB limit.'); return; }
    try { const raw=await file.text(); report=NmapParser.parse(raw,file.name); render(); toast(`Parsed ${report.hosts.length} host record${report.hosts.length===1?'':'s'} from ${report.filename}.`); }
    catch (e) { toast(e.message || 'Could not parse this file.'); }
  }
  function exportSummary() {
    const m=metrics(), lines=['NIGHTWATCH — NMAP SCAN SUMMARY',`File: ${report.filename}`,`Format: ${report.format}`,`Scan date: ${report.scan.date||'Not found'}`,`Hosts: ${report.scan.hostCount} (${report.scan.upCount} up)`,`Open ports: ${report.scan.openCount}`,`Port records: ${report.scan.portCount}`,`Explicit vulnerability findings: ${report.findings.length}`,'','HOSTS',...report.hosts.map(h=>`- ${h.address}${h.hostname?` (${h.hostname})`:''} — ${h.state}; ${h.ports.filter(p=>p.state==='open').length} open ports`),'','OPEN SERVICES',...m.open.map(p=>`- ${p.host} ${p.port}/${p.protocol} ${p.service}${p.version?` — ${p.version}`:''}`),'','EXPLICIT FINDINGS',...(report.findings.map(f=>`- [${f.severity.toUpperCase()}] ${f.title} at ${f.host}${f.port?`:${f.port}`:''}: ${f.description}`)),...(report.findings.length?[]:['- None identified from explicit script labels.']),'', 'Version strings are observations from the scan; they do not confirm vulnerabilities.'];
    const blob=new Blob([lines.join('\n')],{type:'text/plain'}), url=URL.createObjectURL(blob), a=document.createElement('a');a.href=url;a.download=`${report.filename.replace(/\.[^.]+$/,'')}-summary.txt`;a.click();URL.revokeObjectURL(url);toast('Summary exported.');
  }
  $('#browse-button').addEventListener('click',()=>$('#file-input').click()); $('#replace-button').addEventListener('click',()=>$('#file-input').click()); $('#file-input').addEventListener('change',e=>{loadFile(e.target.files[0]);e.target.value='';}); $('#export-button').addEventListener('click',exportSummary);
  $('#side-nav').addEventListener('click',e=>{const b=e.target.closest('[data-tab]');if(b&&report)showTab(b.dataset.tab);});
  const drop=$('#upload-panel'); ['dragenter','dragover'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.add('dragover');})); ['dragleave','drop'].forEach(name=>drop.addEventListener(name,e=>{e.preventDefault();drop.classList.remove('dragover');})); drop.addEventListener('drop',e=>loadFile(e.dataTransfer.files[0]));
  const dlg=$('#help-dialog'); $('#help-button').addEventListener('click',()=>dlg.showModal()); $('.dialog-close',dlg).addEventListener('click',()=>dlg.close()); dlg.addEventListener('click',e=>{if(e.target===dlg)dlg.close();});
})();
